# Generated by Django 4.2.6 on 2023-10-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideosYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.CharField(max_length=300)),
                ('video_id', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'video_youtube',
                'verbose_name_plural': 'videos_youtube',
                'db_table': 'videos_youtube',
            },
        ),
    ]
