# Generated by Django 4.2.6 on 2023-10-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twocanadaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_oficial', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'parceiro',
                'verbose_name_plural': 'parceiros',
                'db_table': 'parceiros',
            },
        ),
    ]
