# Generated by Django 4.2.6 on 2023-10-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twocanadaapp', '0003_sobre_alter_parceiros_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('imagem', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'podcast',
                'verbose_name_plural': 'podcast',
                'db_table': 'podcast',
            },
        ),
        migrations.CreateModel(
            name='Tcexp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'tcexp',
                'verbose_name_plural': 'tcexp',
                'db_table': 'tcexp',
            },
        ),
    ]
